# vim: ts=2 sw=2 et
version: '3.6'

services:
  BTC:
    build: ./bitcoind
    image: kmdplatform_bitcoind
    network_mode: host
    ports:
      # RPC port
      - "127.0.0.1:8332:8332"
      - "127.0.0.1:8333:8333"
    volumes:
      - bitcoin-data:/home/bitcoin
      - shared-data:/home/bitcoin/.shared:ro
    environment:
      - BITCOIN_DATA=${BITCOIN_DATA}
      - BITCOIN_USER_ID=${BITCOIN_USER_ID}
      - BITCOIN_GROUP_ID=${BITCOIN_GROUP_ID}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_BIND=127.0.0.1
      - BITCOIN_RPC_BIND=0.0.0.0
      - BITCOIN_RPC_ALLOWIP=0.0.0.0/0

  KMD:
    build:
      context: ./komodod
      args:
        KOMODO_BRANCH: beta
    image: kmdplatform_komodod
    network_mode: host
    restart: on-failure
    ports:
      - "127.0.0.1:7770:7770"
      # RPC port
      - "127.0.0.1:7771:7771"
    volumes:
      - komodo-data:/home/komodo/.komodo
      - shared-data:/home/komodo/.shared:ro
    environment:
      - KOMODO_RPC_USER=${KOMODO_RPC_USER}
      - KOMODO_RPC_PASSWORD=${KOMODO_RPC_PASSWORD}
      - KOMODO_BIND=127.0.0.1
      - KOMODO_RPC_BIND=0.0.0.0
      - KOMODO_RPC_ALLOWIP=0.0.0.0/0
      - KOMODO_BRANCH=beta
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_RPC_BIND=BTC
      - BTC_PUBKEY=${BTC_PUBKEY}

  CHIPS:
    build:
      context: ./chipsd
      args:
        CHIPS_BRANCH: master
    image: kmdplatform_chipsd
    network_mode: host
    ports:
      - "127.0.0.1:57776:57776"
      # RPC port ?
      - "127.0.0.1:57777:57777"
    volumes:
      - chips-data:/home/chips/.chips
      - shared-data:/home/komodo/.shared:ro
    environment:
      - CHIPS_RPC_USER=${ASSET_RPC_USER}
      - CHIPS_RPC_PASSWORD=${ASSET_RPC_PASSWORD}
      - CHIPS_BIND=127.0.0.1
      - CHIPS_RPC_BIND=0.0.0.0
      - CHIPS_RPC_ALLOWIP=0.0.0.0/0
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_RPC_BIND=BTC
      - KOMODO_RPC_USER=${KOMODO_RPC_USER}
      - KOMODO_RPC_PASSWORD=${KOMODO_RPC_PASSWORD}
      # - KOMODO_RPC_BIND=KMD

  GAME:
    build:
      context: ./gamecreditsd
      args:
        GAME_BRANCH: master
    image: kmdplatform_gamecreditsd
    network_mode: host
    ports:
      # RPC port
      - "127.0.0.1:40001:40001"
      - "40002:40002"
    volumes:
      - gamecredits-data:/home/gamecredits/.gamecredits
      - shared-data:/home/komodo/.shared:ro
    environment:
      - GAME_RPC_USER=${ASSET_RPC_USER}
      - GAME_RPC_PASSWORD=${ASSET_RPC_PASSWORD}
      - GAME_BIND=127.0.0.1
      - GAME_RPC_BIND=0.0.0.0
      - GAME_RPC_ALLOWIP=0.0.0.0/0
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_RPC_BIND=BTC
      - KOMODO_RPC_USER=${KOMODO_RPC_USER}
      - KOMODO_RPC_PASSWORD=${KOMODO_RPC_PASSWORD}
      # - KOMODO_RPC_BIND=KMD

  iguana:
    build:
      context: ./iguana/docker
      args:
        IGUANA_BRANCH: beta
    image: kmdplatform_iguana
    network_mode: "host"
    ports:
      # RPC port
      - "127.0.0.1:7776:7776"
      # to the outside world
      - "0.0.0.0:17775:17775"
    volumes:
      - iguana-data:/home/iguana/.iguana
      - shared-data:/home/iguana/.shared
    environment:
      # - IGUANA_RPC_USER=${IGUANA_RPC_USER}
      # - IGUANA_RPC_PASSWORD=${IGUANA_RPC_PASSWORD}
      - IGUANA_MODE=production
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      # - BITCOIN_RPC_BIND=BTC
      - KOMODO_RPC_USER=${KOMODO_RPC_USER}
      - KOMODO_RPC_PASSWORD=${KOMODO_RPC_PASSWORD}
      # - KOMODO_RPC_BIND=KMD
      - CHIPS_RPC_USER=${ASSET_RPC_USER}
      - CHIPS_RPC_PASSWORD=${ASSET_RPC_PASSWORD}
      - GAME_RPC_USER=${ASSET_RPC_USER}
      - GAME_RPC_PASSWORD=${ASSET_RPC_PASSWORD}

volumes:
  bitcoin-data:
    driver_opts:
      type: none
      device: ${BITCOIN_DATA}
      o: bind
  chips-data:
    driver_opts:
      type: none
      device: ${CHIPS_DATA}
      o: bind
  gamecredits-data:
    driver_opts:
      type: none
      device: ${GAME_DATA}
      o: bind
  komodo-data:
    driver_opts:
      type: none
      device: ${KOMODO_DATA}
      o: bind
  iguana-data:
    driver_opts:
      type: none
      device: ${IGUANA_DATA}
      o: bind
  shared-data:
    driver_opts:
      type: none
      device: ${SHARED_DATA}
      o: bind

networks:
  komodo:
