# vim: ts=2 sw=2 et
version: '3'

services:
  bitcoin:
    container_name: bitcoin
    build: ./bitcoin
    network_mode: "host"
    ports: 
      - "8333:8333"
      # - "8332:8332"
      - "127.0.0.1:833:8332"
    volumes:
      - bitcoin-data:/home/bitcoin
      - shared-data:/home/bitcoin/.shared:ro
    environment:
      - BITCOIN_DATA=${BITCOIN_DATA}
      - BITCOIN_USER_ID=${BITCOIN_USER_ID}
      - BITCOIN_GROUP_ID=${BITCOIN_GROUP_ID}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}

  komodo:
    build: 
      context: ./komodo
    network_mode: "host" 
    ports:
      - "7771:7771"
    volumes:
      - komodo-data:/home/komodo/.komodo
      - shared-data:/home/komodo/.shared:ro
    environment:
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}

  iguana:
    build: 
      context: ./iguana
    network_mode: "host"
    ports:
      - "7778:7778"
      - "7776:7776"
    volumes:
      - iguana-data:/home/iguana/.iguana
      - shared-data:/home/iguana/.shared
      # - bitcoin-data:/home/bitcoin/
      - komodo-data:/home/iguana/.komodo
    environment:
      - IGUANA_WALLET_PASSPHRASE=${IGUANA_WALLET_PASSPHRASE}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}


volumes:
  bitcoin-data:
    driver_opts:
      type: none
      device: ${BITCOIN_DATA}
      o: bind
  komodo-data:
    driver_opts:
      type: none
      device: ${KOMODO_DATA}
      o: bind
  iguana-data:
    driver_opts:
      type: none
      device: ${IGUANA_DATA}
      o: bind
  shared-data:
    driver_opts:
      type: none
      device: ${SHARED_DATA}
      o: bind
