# vim: ts=2 sw=2 et
version: '3.6'

services:
  iguana:
    build:
      args:
        IGUANA_BRANCH: dev
    image: kmdplatform_iguana_dev
    # image: kmdplatform_iguana_dev_patchkez:latest
    environment:
    # If this variable is set to dev or jl777, iguana will be started in testnet
      - IGUANA_MODE=production

  KMD:
    build:
      args:
        KOMODO_BRANCH: dev
    image: kmdplatform_komodod_dev

  CHIPS:
    build:
      args:
        CHIPS_BRANCH: dev
    image: kmdplatform_chipsd_dev

