# vim: ts=2 sw=2 et
version: '3'

services:
  komodo:
    build: 
      context: ./komodo
      args:
        KOMODO_BRANCH: dev
    image: kmdplatform_komodo_dev

  iguana:
    # depends_on:
    #  - komodo
    build: 
      context: ./iguana
      args:
        IGUANA_BRANCH: dev
    image: kmdplatform_iguana_dev
    environment:
    # If this variable is set to dev, iguana will be started in testnet 
      - IGUANA_MODE=dev 
